# ~/.config/hypr/hyprpaper.conf
splash = false

wallpaper {
    monitor = eDP-2
    path = ~/.config/hypr/backgrounds/Anime-Purple-eyes.png
    fit_mode = cover
    #order = random
    #timeout = 1800
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/backgrounds/industrial-moon.jpg    #order = random
    fit_mode = cover
    #timeout = 1800
}
