# Main background
source = ~/.config/themes/current/next-theme/hyprlock.conf


general {
    ignore_empty_input = true
}

animations {
    enabled = false
}

# --- Configuración del Fondo con Blur Avanzado ---
background {
    monitor =
    path = ~/.config/hypr/backgrounds/Anime-Purple-eyes.png
    color = $color
    
    # Calibración del Blur (Efecto esmerilado profundo)
    blur_passes = 3           # Número de pasadas de filtrado (3 es el dulce balance rendimiento/calidad)
    blur_size = 7             # Radio del blur en píxeles (¡Crucial para que funcione!)
    noise = 0.0117            # Añade una textura de grano muy fina para romper bandas de color
    contrast = 0.8916         # Mantiene los oscuros profundos bajo el blur
    brightness = 0.75         # Atenúa ligeramente la imagen de fondo para que resalte el login
    vibrancy = 0.2000         # Satura sutilmente los colores extraídos del wallpaper
}

# --- Input Field Estilo Minimalista / Industrial ---
input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = <span foreground="##f6dcac">Enter Password</span>  # Pone el placeholder a juego con tu paleta
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0              # Mantiene el look angular agresivo
    shadow_passes = 1         # Añadido 1 pasada suave para separar el input plano del fondo desenfocado
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.3)
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
