general {
    lock_cmd = pidof hyprlock || hyprlock       
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = sleep 1 && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_dbus_inhibit = false                 
}

# ---------- STAGE 1: ATENUAR PANTALLA ----------
# Reduce el brillo al mínimo para ahorrar energía, pero mantiene la sesión abierta.
listener {
    timeout = 60                                 # 2.5 Minutos
    on-timeout = brightnessctl -s set 10          # Guarda brillo actual y baja a 10
    on-resume = brightnessctl -r                  # Restaura el brillo exacto que tenías
}

# ---------- STAGE 2: BLOQUEAR SESIÓN ----------
# Lanza hyprlock. Al mover el mouse verás la pantalla de bloqueo pidiendo pass.
listener {
    timeout =  300                                # 5 Minutos
    on-timeout = loginctl lock-session            # Llama al lock_cmd de la sección general
}

# ---------- STAGE 3: APAGAR MONITORES (DPMS) ----------
# Corta la señal de video. Los monitores entran en stand-by profundo.
listener {
    timeout = 330                                 # 5.5 Minutos
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    # Apaga pantallas nativamente
    # Al regresar, encendemos y forzamos a Hyprland a re-evaluar los monitores conectados
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && hyprctl reload
}
# ---------- STAGE 4: SUSPENDER EL SISTEMA ----------
# Envía el equipo a RAM (S3 / Modern Standby). 
# Al despertar, gracias a before_sleep_cmd, lo primero que verás será hyprlock.
listener {
    timeout =   600                                 # 10 Minutos
    on-timeout = systemctl suspend                # Suspensión estándar administrada por systemd
}
