# ~/.config/hypr/hyprpaper.conf
splash = false

wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/backgrounds
    fit_mode = cover
    order = random
    timeout = 1800
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/backgrounds
    order = random
    fit_mode = cover
    timeout = 1800
}