# ---------------------------------------------------------------------
# Theme: Transparent Prism - Lavender
# ---------------------------------------------------------------------

# Fondos, Opacidad y Efectos
background = #100d17
background-opacity = 0.96
background-blur = true

# Colores Principales
foreground = #f7f2ff
cursor-color = #f7f2ff
selection-background = #383540
selection-foreground = #f7f2ff

# Terminal ANSI Palette (0-15)

# Black (neutral_2 / neutral_4)
palette = 0=#2e2b3a
palette = 8=#42404a

# Red (accent_pink / bright_red)
palette = 1=#fc618c
palette = 9=#fc618c

# Green (accent_green / bright_green)
palette = 2=#7ad98f
palette = 10=#7ad98f

# Yellow (accent_yellow / ext_yellow)
palette = 3=#fce666
palette = 11=#fce666

# Blue (accent_indigo / ext_indigo)
palette = 4=#948ae3
palette = 12=#948ae3

# Magenta (accent_purple / ext_purple)
palette = 5=#948ae3
palette = 13=#948ae3

# Cyan (accent_blue / ext_blue)
palette = 6=#59d4e6
palette = 14=#59d4e6

# White (neutral_7 / neutral_10)
palette = 7=#706e78
palette = 15=#f7f2ff