#!/bin/bash

if pgrep -x hypridle >/dev/null; then
  echo '{"text": ""}'
else
  echo '{"text": "󱫖", "tooltip": "Idle lock disabled", "class": "active"}'
fi



"on-click": "~/.config/rofi/scripts/toggle-idle",
    "exec": "~/.config/rofi/scripts/idle",

