#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Name:        is-ac.sh
# Description: Returns true (exit 0) if AC power is connected to the system.
# Style:       coffee-dots ☕
# -----------------------------------------------------------------------------

# --- ROASTING LOGIC ---------------------------------------------------------

for ac in /sys/class/power_supply/AC* /sys/class/power_supply/ADP*; do
    [[ -r "$ac/online" && $(cat "$ac/online") == "1" ]] && exit 0
done

# Grid power disconnected (Running on beans battery)
exit 1